const fs = require('fs')

const makeId = (path, method = null) => `${method ? method+'_' : ''}${path.toLowerCase().substr(1).replace('/','_').replace(':', '-')}`

const resource = (input, name, path_part, parent_id = '${module.api.root_resource_id}') => `
resource "aws_api_gateway_resource" "${name}" {
  rest_api_id = "${input.rest_api_id}"
  parent_id   = "${parent_id}"
  path_part   = "${path_part.substr(0,1) === ':' ? '{'+path_part.substr(1)+'}' : path_part}"
}
`

const endpoint = (input, name, id, src) => `
module "${name}" {
  source             = "${input.source}"
  name               = "${input.name}"
  #security_group_ids = [${input.security_group_ids ? '"'+input.security_group_ids+'"' : ''}]
  #private_subnet_ids = [${input.private_subnet_ids ? '"'+input.private_subnet_ids+'"' : ''}]
  rest_api_id        = "${input.rest_api_id}"
  resource_id        = "\${aws_api_gateway_resource.${id}.id}"
  http_method        = "GET"
  stage_name         = "${input.stage_name}"
  resource_path      = "\${aws_api_gateway_resource.${id}.path}"
  source_dir         = "\${path.module}/${src}"
}
`

// const deployment = (input, deps) => `
// resource "aws_api_gateway_deployment" "main" {
//   depends_on = ["${deps.join('","')}"]
//   rest_api_id = "${input.rest_api_id}"
//   stage_name = "${input.stage_name}"
// }`


const resources = {}

const buildResources = (input, path) => {
  const parts = path.substr(1).split('/')
  const paths = []
  let last_id = null
  while(parts.length) {
    paths.push(parts.shift())
    const id = makeId(`/${paths.join('/')}`)
    console.log(id, paths[paths.length-1])
    if (resources[id]) {
      last_id = id
      continue;
    }

    if (paths.length === 1) {
      output += resource(input, id, paths[paths.length-1])
    } else {
      output += resource(input, id, paths[paths.length-1], `\${aws_api_gateway_resource.${last_id}.id}`)
    }

    resources[id] = true

    last_id = id
  }

  return last_id
}

// Run
const input = JSON.parse(fs.readFileSync('routes.json'))
input.args = Object.assign({
  "source": "../../public-api-endpoint",
  "name": "${local.name}",
  "security_group_ids": null,
  "private_subnet_ids": null,
  "rest_api_id": "${module.api.rest_api_id}",
  "stage_name": "${module.api.stage_name}"
}, input.args)
let output = '# ***** Generated by Makefile *****'

//const deps = []
input.routes.forEach((route) => {
  const name = makeId(route.path, route.method)
  const id = buildResources(input.args, route.path)
  output += endpoint(input.args, name, id, route.src)
  //deps.push(`\${module.${name}}`)
})

//output += deployment(input.args, deps)

console.log( output )

fs.writeFileSync('routes.tf', output, 'utf8')
